# Generated by Django 4.2.30 on 2026-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Bachelor of Computer Applications', max_length=200)),
                ('code', models.CharField(help_text='e.g., BCA', max_length=20, unique=True)),
                ('description', models.TextField()),
                ('duration_years', models.PositiveIntegerField(default=3, help_text='Duration of course in years')),
                ('eligibility', models.CharField(help_text='e.g., 10+2 with Mathematics/CS or equivalent with 45% marks', max_length=300)),
                ('seats', models.PositiveIntegerField(default=60)),
                ('image', models.ImageField(blank=True, help_text='Upload course cover image', null=True, upload_to='courses/')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(help_text='e.g., Assistant Professor, HOD', max_length=150)),
                ('department', models.CharField(help_text='e.g., Computer Science, Management', max_length=150)),
                ('qualification', models.CharField(help_text='e.g., Ph.D, M.Tech, MBA', max_length=250)),
                ('image', models.ImageField(blank=True, help_text='Upload faculty passport size photo', null=True, upload_to='faculty/')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('category', models.CharField(choices=[('campus', 'Campus Infrastructure'), ('labs', 'Labs & Library'), ('events', 'Events & Seminars'), ('sports', 'Sports & Activities')], default='campus', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this notice on the notice board')),
                ('is_urgent', models.BooleanField(default=False, help_text='Highlight notice in red/marquee')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
