# Generated by Django 4.2.30 on 2026-06-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading on the slide', max_length=200)),
                ('tag', models.CharField(blank=True, help_text='e.g., Admissions 2026 Open', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Subtitle description text')),
                ('image', models.ImageField(help_text='Upload background banner image', upload_to='carousel/')),
                ('button_text', models.CharField(default='Know More', max_length=50)),
                ('button_link', models.CharField(default='/courses/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (ascending)')),
                ('is_active', models.BooleanField(default=True, help_text='Tick to display on homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
